import { Ionicons } from '@expo/vector-icons';
import { useNavigation } from '@react-navigation/native';
import type { NativeStackNavigationProp, NativeStackScreenProps } from '@react-navigation/native-stack';
import React, { useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { useAppData } from '../AppContext';
import type { RootStackParamList } from '../navigationTypes';
import { updateShopStatusWithAudit, updateUserRolesWithAudit } from '../../modules/admin/adminRepository';
import type { BarberShopStatus } from '../../modules/barber-shops/types';
import type { UserRole } from '../../modules/users/types';
import { AppointmentCard, Banner, EmptyState, LoadingState, PremiumHero, Screen, SectionHeader, ShopCard, StatusPill } from '../../shared/components/AppUI';
import { Field, SelectField } from '../../shared/components/FormControls';
import { PrimaryButton } from '../../shared/components/PrimaryButton';
import { colors, spacing, typography } from '../../shared/theme';
import { resolveShopImage } from '../../shared/assets/demoAssets';

type RootNavigation = NativeStackNavigationProp<RootStackParamList>;

export function AdminHomeScreen() {
  const navigation = useNavigation<RootNavigation>();
  const { data, loading } = useAppData();
  if (loading) return <LoadingState />;
  const pending = data.appointments.filter((item) => item.status === 'pending');
  const suspended = data.shops.filter((item) => item.status === 'suspended');
  return <Screen eyebrow="Administración" title="Estado de TapFade"><PremiumHero eyebrow="Operación" subtitle={`${pending.length} solicitudes pendientes · ${suspended.length} negocios suspendidos`} title={pending.length || suspended.length ? 'Hay casos por revisar.' : 'La plataforma está en orden.'} /><View style={styles.metrics}><Metric label="Usuarios" value={String(data.users.length)} /><Metric label="Negocios" value={String(data.shops.length)} /><Metric label="Citas" value={String(data.appointments.length)} /></View><SectionHeader title="Actividad reciente" />{pending.slice(0, 4).map((item) => <AppointmentCard client={`${item.clientName} · ${item.barberName}`} date={item.startAt.toLocaleString('es-MX')} key={item.id} onPress={() => navigation.navigate('AppointmentDetail', { appointmentId: item.id, source: 'admin' })} service={item.serviceName} status={item.status} />)}{pending.length === 0 ? <EmptyState icon="shield-checkmark-outline" message="No hay solicitudes operativas pendientes." title="Sin alertas" /> : null}</Screen>;
}

export function AdminUsersScreen() {
  const navigation = useNavigation<RootNavigation>(); const { data, loading } = useAppData(); const [query, setQuery] = useState(''); const [role, setRole] = useState<'all' | UserRole>('all');
  const users = useMemo(() => data.users.filter((item) => (role === 'all' || item.roles.includes(role)) && (!query.trim() || `${item.displayName} ${item.email}`.toLowerCase().includes(query.trim().toLowerCase()))), [data.users, query, role]); if (loading) return <LoadingState />;
  return <Screen eyebrow="Administración" title="Usuarios"><Field label="Buscar" onChangeText={setQuery} placeholder="Nombre o correo" value={query} /><SelectField label="Rol" onChange={setRole} options={[{ label: 'Todos', value: 'all' }, { label: 'Clientes', value: 'client' }, { label: 'Barberos', value: 'barber' }, { label: 'Dueños', value: 'owner' }, { label: 'Admins', value: 'admin' }]} value={role} />{users.length ? users.map((user) => <Pressable key={user.uid} onPress={() => navigation.navigate('AdminUserDetail', { userId: user.uid })} style={styles.row}><View style={styles.icon}><Ionicons color={colors.blue} name="person-outline" size={20} /></View><View style={styles.flex}><Text style={styles.title}>{user.displayName || user.email}</Text><Text style={styles.muted}>{user.email}</Text></View><Text style={styles.badge}>{user.roles.filter((item) => item !== 'client').join(', ') || 'cliente'}</Text></Pressable>) : <EmptyState message="No hay usuarios que coincidan." title="Sin resultados" />}</Screen>;
}

export function AdminUserDetailScreen({ navigation, route }: NativeStackScreenProps<RootStackParamList, 'AdminUserDetail'>) {
  const { data, profile, refresh } = useAppData(); const user = data.users.find((item) => item.uid === route.params.userId); const [roles, setRoles] = useState<UserRole[]>(user?.roles ?? ['client']); const [message, setMessage] = useState<string | null>(null); const [saving, setSaving] = useState(false); if (!user || !profile) return <Screen eyebrow="Usuario" title="No disponible"><EmptyState icon="person-remove-outline" message="Este perfil ya no existe o no tienes acceso." title="Usuario no encontrado" /></Screen>;
  function toggle(role: UserRole) { if (role === 'client') return; if (role === 'barber' || role === 'owner') { setMessage('Los roles de negocio se asignan mediante alta o invitación para conservar la membresía.'); return; } setRoles((current) => current.includes(role) ? current.filter((item) => item !== role) : [...current, role]); }
  async function save() { if (saving) return; if (user!.uid === profile!.uid && !roles.includes('admin')) { setMessage('No puedes retirar tu propio acceso administrativo.'); return; } setSaving(true); setMessage(null); try { await updateUserRolesWithAudit(user!.uid, roles, profile!.uid); await refresh(); navigation.goBack(); } catch (caught) { setMessage(caught instanceof Error ? caught.message : 'No fue posible guardar los roles.'); } finally { setSaving(false); } }
  return <Screen eyebrow="Usuario" title={user.displayName || user.email}><View style={styles.summary}><Text style={styles.muted}>{user.email}</Text><Text style={styles.title}>Roles autorizados</Text><View style={styles.chips}>{(['barber','owner','admin'] as UserRole[]).map((role) => <Pressable accessibilityRole="checkbox" accessibilityState={{ checked: roles.includes(role) }} key={role} onPress={() => toggle(role)} style={[styles.chip, roles.includes(role) && styles.chipActive]}><Text style={[styles.chipText, roles.includes(role) && styles.chipTextActive]}>{role}</Text></Pressable>)}</View></View>{message ? <Banner message={message} tone="danger" /> : null}<PrimaryButton label="Guardar permisos" loading={saving} onPress={() => void save()} /></Screen>;
}

export function AdminShopsScreen() { const navigation = useNavigation<RootNavigation>(); const { data, loading } = useAppData(); const [query, setQuery] = useState(''); const [status, setStatus] = useState<'all' | BarberShopStatus>('all'); const shops = data.shops.filter((item) => (status === 'all' || item.status === status) && (!query.trim() || `${item.name} ${item.address}`.toLowerCase().includes(query.trim().toLowerCase()))); if (loading) return <LoadingState />; return <Screen eyebrow="Administración" title="Negocios"><Field label="Buscar" onChangeText={setQuery} value={query} /><SelectField label="Estado" onChange={setStatus} options={[{ label: 'Todos', value: 'all' }, { label: 'Activos', value: 'active' }, { label: 'Pausados', value: 'paused' }, { label: 'Suspendidos', value: 'suspended' }]} value={status} />{shops.length ? shops.map((shop) => <Pressable key={shop.id} onPress={() => navigation.navigate('AdminShopDetail', { shopId: shop.id })}><ShopCard address={`${shop.address} · ${shop.status}`} image={resolveShopImage(shop)} name={shop.name} /></Pressable>) : <EmptyState icon="business-outline" message="Ajusta la búsqueda o el estado seleccionado." title="Sin negocios" />}</Screen>; }

export function AdminShopDetailScreen({ navigation, route }: NativeStackScreenProps<RootStackParamList, 'AdminShopDetail'>) { const { data, profile, refresh } = useAppData(); const [message, setMessage] = useState<string | null>(null); const [saving, setSaving] = useState(false); const shop = data.shops.find((item) => item.id === route.params.shopId); const owner = shop ? data.users.find((item) => item.uid === shop.ownerId) : null; if (!shop || !profile) return <Screen eyebrow="Negocio" title="No disponible"><EmptyState icon="business-outline" message="El negocio ya no existe o no tienes acceso." title="Negocio no encontrado" /></Screen>; async function setStatus(status: BarberShopStatus) { if (saving) return; setSaving(true); setMessage(null); try { await updateShopStatusWithAudit(shop!.id, status, profile!.uid); await refresh(); navigation.goBack(); } catch (caught) { setMessage(caught instanceof Error ? caught.message : 'No fue posible cambiar el estado.'); } finally { setSaving(false); } } return <Screen eyebrow="Negocio" title={shop.name}><ShopCard address={shop.address} image={resolveShopImage(shop)} name={shop.name} /><StatusPill status={shop.status} /><View style={styles.summary}><Text style={styles.muted}>{shop.description}</Text><Text style={styles.muted}>Propietario: {owner?.displayName || owner?.email || 'Perfil no disponible'}</Text></View>{message ? <Banner message={message} tone="danger" /> : null}{shop.status === 'suspended' ? <PrimaryButton label="Restaurar negocio" loading={saving} onPress={() => void setStatus('active')} /> : <PrimaryButton label="Suspender negocio" loading={saving} onPress={() => void setStatus('suspended')} variant="danger" />}</Screen>; }

export function AdminAppointmentsScreen() { const navigation = useNavigation<RootNavigation>(); const { data, loading } = useAppData(); const [status, setStatus] = useState<'all' | 'pending' | 'confirmed' | 'completed' | 'cancelled'>('all'); if (loading) return <LoadingState />; const items = data.appointments.filter((item) => status === 'all' || item.status === status).sort((left, right) => right.startAt.getTime() - left.startAt.getTime()); return <Screen eyebrow="Administración" title="Citas"><SelectField label="Estado" onChange={setStatus} options={[{ label: 'Todas', value: 'all' }, { label: 'Pendientes', value: 'pending' }, { label: 'Confirmadas', value: 'confirmed' }, { label: 'Completadas', value: 'completed' }, { label: 'Canceladas', value: 'cancelled' }]} value={status} />{items.length ? items.map((item) => <AppointmentCard client={`${item.clientName} · ${item.barberName}`} date={item.startAt.toLocaleString('es-MX')} key={item.id} onPress={() => navigation.navigate('AppointmentDetail', { appointmentId: item.id, source: 'admin' })} service={item.serviceName} status={item.status} />) : <EmptyState icon="calendar-outline" message="No hay citas con el estado seleccionado." title="Sin resultados" />}</Screen>; }

function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.muted}>{label}</Text></View>; }
const styles = StyleSheet.create({ badge: { color: colors.blue, fontFamily: typography.bodyBold, fontSize: 11 }, chip: { borderColor: colors.coolGrey, borderRadius: 14, borderWidth: 1, padding: spacing.md }, chipActive: { backgroundColor: colors.graphite }, chipText: { color: colors.steel, fontFamily: typography.bodyBold }, chipTextActive: { color: colors.surface }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, flex: { flex: 1 }, icon: { alignItems: 'center', backgroundColor: colors.blueGlow, borderRadius: 12, height: 40, justifyContent: 'center', width: 40 }, metric: { backgroundColor: colors.surface, borderRadius: 18, flex: 1, gap: spacing.xs, padding: spacing.md }, metrics: { flexDirection: 'row', gap: spacing.sm }, metricValue: { color: colors.graphite, fontFamily: typography.displayBold, fontSize: 21 }, muted: { color: colors.muted, fontFamily: typography.body, fontSize: 13 }, row: { alignItems: 'center', backgroundColor: colors.surface, borderRadius: 18, flexDirection: 'row', gap: spacing.md, padding: spacing.md }, summary: { backgroundColor: colors.surface, borderRadius: 18, gap: spacing.md, padding: spacing.lg }, title: { color: colors.graphite, fontFamily: typography.bodyBlack, fontSize: 15 } });
